# Backend configuration
backend:
  name: backendbgi
  image: docker.io/rkaeffer/codelab-gitops-backend:1.0.0
  containerPort: 8080
  host: 	bgiraud-backend.codelab.cloud-sp.eu
  service:
    port: 443